### PR TITLE
3.6 add native plugins

### PR DESCRIPTION
**Pull request by PatriceJiang**
README https://github.com/cocos/cocos-example-projects/blob/8daaa94f908f84d370c829b9aa39c1f6a1c4c176/native-plugin/README.md

### CODE REVIEW

**Comment by PatriceJiang** [comment]
@minggo  please review

**Comment by minggo** [comment]
errro.PNG -> error.png ?

**Comment by PatriceJiang** [comment]
The file name and path does work

**Comment by minggo** [comment]
Yep, I know it can work. Just use the same style.

**Comment by PatriceJiang** [comment]
Fixed

**Pull request merged**
